# Generated by Django 4.0.6 on 2022-07-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parselyBackEnd', '0002_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.TextField(),
        ),
    ]
