# Generated by Django 4.0.6 on 2022-07-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parselyBackEnd', '0003_alter_recipe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
    ]
