# Generated by Django 4.0.6 on 2022-08-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parselyBackEnd', '0006_recipe_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='extra',
        ),
    ]
